light.guest_bathroom_vanity_light_level_5_0:
  refresh_value: true
  delay: 3
  polling_intensity: 1
light.guest_bathroom_fan_light_level_7_0:
  refresh_value: true
  delay: 3
  polling_intensity: 1

sensor.front_door_alarm_level_2_1:
  ignored: true
sensor.back_door_alarm_level_3_1:
  ignored: true
sensor.front_door_alarm_type_2_0:
  ignored: true
sensor.back_door_alarm_type_3_0:
  ignored: true
sensor.front_door_burglar_2_10:
  ignored: true
sensor.back_door_burglar_3_10:
  ignored: true
sensor.front_door_sourcenodeid_2_2:
  ignored: true
sensor.back_door_sourcenodeid_3_2:
  ignored: true
sensor.front_door_sourcenodeid_10_2:
  ignored: true
  
sensor.energy_meter_exporting_9_32:
  ignored: true
sensor.energy_meter_exporting_9_32_2:
  ignored: true
sensor.energy_meter_exporting_9_32_3:
  ignored: true
sensor.energy_meter_previous_reading_9_1:
  ignored: true
sensor.energy_meter_previous_reading_9_1_2:
  ignored: true
sensor.energy_meter_previous_reading_9_1_3:
  ignored: true
sensor.energy_meter_power_9_8:
  ignored: true
sensor.energy_meter_power_9_8_2:
  ignored: true
sensor.energy_meter_power_9_8_3:
  ignored: true
sensor.energy_meter_interval_9_2:
  ignored: true
sensor.energy_meter_interval_9_2_2:
  ignored: true
sensor.energy_meter_interval_9_2_3:
  ignored: true
  
sensor.garage_multisensor_sourcenodeid_8_2:
  ignored: true
sensor.garage_multisensor_ultraviolet_8_27:
  ignored: true