light.guest_bathroom_vanity_light_level:
  refresh_value: true
  delay: 3
  polling_intensity: 1
light.guest_bathroom_fan_light_level:
  refresh_value: true
  delay: 3
  polling_intensity: 1
switch.living_room_smart_plug:
  refresh_value: true
  delay: 3
sensor.front_door_alarm_level:
  ignored: true
sensor.back_door_alarm_level:
  ignored: true
sensor.front_door_alarm_type:
  ignored: true
sensor.back_door_alarm_type:
  ignored: true
sensor.front_door_burglar:
  ignored: true
sensor.back_door_burglar:
  ignored: true
sensor.front_door_sourcenodeid:
  ignored: true
sensor.back_door_sourcenodeid:
  ignored: true
sensor.front_door_sourcenodeid_2:
  ignored: true
sensor.energy_meter_exporting:
  ignored: true
sensor.energy_meter_exporting_2:
  ignored: true
sensor.energy_meter_exporting_3:
  ignored: true
sensor.energy_meter_previous_reading:
  ignored: true
sensor.energy_meter_previous_reading_2:
  ignored: true
sensor.energy_meter_previous_reading_3:
  ignored: true
sensor.energy_meter_power_4:
  ignored: true
sensor.energy_meter_power_5:
  ignored: true
sensor.energy_meter_power_6:
  ignored: true
sensor.energy_meter_interval:
  ignored: true
sensor.energy_meter_interval_2:
  ignored: true
sensor.energy_meter_interval_3:
  ignored: true
sensor.garage_multisensor_sourcenodeid:
  ignored: true
sensor.garage_multisensor_ultraviolet:
  ignored: true
sensor.garage_side_door_sourcenodeid:
  ignored: true
  polling_intensity: 0
binary_sensor.garage_side_door_sensor:
  ignored: true
  polling_intensity: 0
binary_sensor.garage_inside_door_sensor:
  ignored: true
  polling_intensity: 0
binary_sensor.nursery_door_sensor:
  ignored: true
  polling_intensity: 0
sensor.garage_inside_door_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.front_door_lock_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.garage_door_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.water_sensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.living_room_multisensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
binary_sensor.living_room_multisensor_sensor:
  ignored: true
  polling_intensity: 0
binary_sensor.nursery_window:
  ignored: true
  polling_intensity: 0
binary_sensor.office_window:
  ignored: true
  polling_intensity: 0
sensor.office_window_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.nursery_window_sourcenodeid:
  ignored: true
  polling_intensity: 0
binary_sensor.master_bedroom_window_sensor:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_window_sourcenodeid:
  ignored: true
  polling_intensity: 0
binary_sensor.master_bedroom_window2:
  ignored: true
  polling_intensity: 0
sensor.master_bedroom_window2_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.guest_bathroom_multisensor_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.guest_bathroom_multisensor_homehealth:
  ignored: true
  polling_intensity: 0
sensor.guest_bathroom_multisensor_emergency:
  ignored: true
  polling_intensity: 0
